### ISSUE TITLE
Add "call" constraint to allow adding side effects in expect()

### ISSUE THREAD

**Issue by smod** [cgreen-devs/cgreen#103]
I need something like `expect(__wrap_rename, will_return(-1), will_set_errno(EXDEV))`. I digged into CGreen's internals and found out that a `ConstraintType::CALL` value exists but is currently unused.

Is it planned to add something like

```
Constraint *create_callback_constraint(void (*callback)(void *), void *data)
```
?

That would be great!

**Comment by thoni56** [comment]
a) Could you give a more detailed example?

b) My first thought would be to add the side effect to the mocked function:

    int _wrap_rename(char *something) {
        errno = EXDEV;    /* "Sideeffect */
        return (int)mock(something);
   }

Would this work? Or do you need different side effects for each invocation?

c) I don't know exactly where `CALL` comes from or what the thoughts were when that was created. Possibly @matthargett knows more on this. `git blame` points to @joaohf which has not been active on the project for a long time.

d) Seems a good idea.

**Comment by smod** [comment]
I indeed need to tweak `errno` in a more clever way, concretly, I've got this:

```
Ensure(mylib_internal_file_move_ut)
{
    struct stat st;

    /* rename failed (not same filesystem), falling back to copy, new file path is invalid */
    expect(__wrap_rename, will_return(-1));
    mylib_mock_push_errno(__wrap_rename, EXDEV);
    expect(__wrap_open, will_return(-1));
    mylib_mock_push_errno(__wrap_open, ENOENT);
    mylib_mock_enable(true);
    assert_that(mylib_internal_file_move("src", "dest", MYLIB_PERM_PRESERVE),
                is_equal_to(MYLIB_STATUS_INVALID_ARGUMENT));
    mylib_mock_enable(false);
}
```

My wrapper are implemented as:

```
int __wrap_rename(const char *oldpath, const char *newpath)
{
    if (mylib_mock_enabled)
    {
        mylib_mock_pop_errno(__wrap_rename);
        return (int) mock(oldpath, newpath);
    }

    return __real_rename(oldpath, newpath);
}
```

As you can read, I achieved what I wanted by tweaking my wrapper, it works, but it would have been more convenient to write 

```
    expect(__wrap_rename, will_return(-1), will_set_errno(EXDEV));
```

instead of

```
    expect(__wrap_rename, will_return(-1));
    mylib_mock_push_errno(__wrap_rename, EXDEV);
```

I would have implemented `will_set_errno` myself by creating my own `Constraint*`, but as I read cgreen's `src/mocks.c`, my `ConstraintType` must be either `RETURN_VALUE` (which is not what I want) or `CONTENT_SETTER` (which won't work in my case since it is not an actual mock parameter).

At first sight, I thought that `CALL` was what I was looking for, but it's currently unused. Seems IMHO to be a good candidate for something like

```
Constraint *create_callback_constraint(void (*callback)(void *), void *data)
```

**Comment by thoni56** [comment]
Thanks for the example! At least that might help others with the same need until we implement something to help with this.

I'm thinking along the lines of

    expect(<func>, <constraint>, with_sideeffect(<sideeffect_func>));
