### ISSUE TITLE
Rewrite readme.md

### ISSUE THREAD

**Issue by thoni56** [cgreen-devs/cgreen#11]
We need a better and more 'marketing' style readme.md for display on the GitHub landing page. I think it should showcase the very readable style of the tests instead of wallowing in historical facts ;-)

But we'd still like to keep some of the current information somewhere.

**Comment by thoni56** [comment]
I'll take a stab at this, as a break from the docs rewrite...

**Comment by matthargett** [comment]
agreed. fast build, clean code, highly portable, test auto-discovery without abuse of static initializers or globals, extensible without recompiling, same modern syntax across C and C++, process isolation for each test prevents intermittent failures, built-in mocking for C, compatible with mockitopp and other C++ mocking libraries.

**Comment by thoni56** [comment]
I'll add those.

What do you mean by "extensible without compiling"?

**Comment by thoni56** [comment]
Could probably be improved further, and please do so if you feel you have an improvement.
