### ISSUE TITLE
XML reporter doesn't list failed tests

### ISSUE THREAD

**Issue by emericl** [cgreen-devs/cgreen#111]
There is a problem with the xml reporter.
It only generate XML output for failed tests when running a single test and don't work when running a test suite.

The problem is that tests are executed in separate processes when using test suites.
The reporter's functions (xml_show_fail and xml_show_skip) are executed in the child process to accumulate data but this data can't be returned to parent process to put it in the XML file (xml_reporter_finish_test) because the two process don't share the same memory space.

I don't know how to correct this, maybe using IPC.
For my project I've made a "dirty patch".
I have modified xml_reporter_start_test() so that the "testcase" tag is closed with time = 0 and I modified  xml_show_fail() and xml_show_skip() so they can write in the XML file.
[xml_reporter.c.diff.txt](https://github.com/cgreen-devs/cgreen/files/657708/xml_reporter.c.diff.txt)

**Comment by thoni56** [comment]
Thanks for your report! The problem have been identified and there is a PR #112 that should address this problem.
