### ISSUE TITLE
cgreen install results in cgreen_value.h not found

### ISSUE THREAD

**Issue by kammce** [cgreen-devs/cgreen#126]
In file included from /usr/local/include/cgreen/internal/cpp_assertions.h:4:0,
                 from /usr/local/include/cgreen/internal/assertions_internal.h:7,
                 from /usr/local/include/cgreen/assertions.h:4,
                 from /usr/local/include/cgreen/cgreen.h:7,
                 from Tests/Tracker/Tests-Main.cpp:1:
/usr/local/include/cgreen/constraint.h:5:33: fatal error: cgreen/cgreen_value.h: No such file or directory

Error on Ubuntu 16.04LTS.

I went through 
make
make test
sudo make install

**Comment by kammce** [comment]
Fixed it. Seems that the cgreen_value.h file is not moved to /usr/local/include/cgreen when doing make install.

**Comment by thoni56** [comment]
Thanks. I also discovered that a few days ago but must have missed to push that. I'll fix that as soon as I'm at a computer.

**Comment by thoni56** [comment]
Should be fixed with https://github.com/cgreen-devs/cgreen/commit/5d9bc5aa27ebb0007d807666f4f3a82ff828ebab.
