### ISSUE TITLE
Add warning for parenthesis typo in expect()

### ISSUE THREAD

**Issue by awilke** [cgreen-devs/cgreen#129]
When using mocks, it's possible to make this kind of mistake:
```
expect(mocked_func, will_return(true)),
    when(param, is_equal_to(5));
```
Note the extra parenthesis at the end of the first line. Thanks to the comma operator, this effectively creates a mock expectation which silently ignores the constraints on its parameter(s), and passes the test case.

An improvement would be to add the `warn_unused_result` attribute to the `when_()` function, so that the above excerpt would result in a compiler error:
```
Constraint *when_() __attribute__((warn_unused_result));
```
The resulting warning is not super clear, but at least it's an indication that the test would not behave as expected.

**Comment by thoni56** [comment]
Thanks for that excellent idea! Although, for portability I'd probably wrap the GNU-ism in something like

    #ifdef __GNUC__
    #define WARN_UNUSED_RESULT __attribute__((warn_unused_result))
    #else 
    #define WARN_UNUSED_RESULT
    #endif
