### ISSUE TITLE
CGREEN_NO_FORK changes expect behavior

### ISSUE THREAD

**Issue by derfian** [cgreen-devs/cgreen#158]
I have a test case that fails for some reason when CGREEN_NO_FORK is set. In my particular case, an expected function call was not made. I'm trying to figure out if this is a bug in my code or in cgreen. I would appreciate some aid in finding out what's to blame here.

> [cendio@pairstation tests]$ cgreen-runner resize
> Running "resize" (6 tests)...
>   "Resize": 30 passes in 9ms.
> Completed "resize": 30 passes in 9ms.

> [cendio@pairstation tests]$ CGREEN_NO_FORK=1 cgreen-runner resize
> Running "resize" (6 tests)...
> resize_test.c:310: Failure: Resize -> UsingRDPEDISPHonoursServerMaximumSessionSizeLimit 
> 	Expected call was not made to mocked function [rdpedisp_set_session_size]
> 
> resize_test.c:352: Failure: Resize -> UsingRDPEDISPHonoursServerMinimumSessionSizeLimit 
> 	Expected call was not made to mocked function [rdpedisp_set_session_size]
> 
> resize_test.c:392: Failure: Resize -> UsingRDPEDISPHonoursServerSessionWidthConstraintMustBeEven 
> 	Expected call was not made to mocked function [rdpedisp_set_session_size]
> 
>   "Resize": 24 passes, 3 failures in 2ms.
> Completed "resize": 24 passes, 3 failures in 2ms.

**Comment by thoni56** [comment]
One common cause of such behaviour difference between forking and no-forking is memory corruption. In the forking case the code under test has its own memory overwriting stacks, buffers etc. and might go unnoticed since the child is just about to be terminated. Such overwrites might affect `cgreen` data structures when running in the same process.

Could that be the case here?

**Comment by derfian** [comment]
It's certainly possible, although probably unlikely. I will try to find time to run it with the address sanitizer or valgrind to see if there is anything indicating memory issues to rule it out though.

I also know that the code under test is heavy on global variables and I'm thinking forking might protect me from the tests leaking state between each other.

**Comment by thoni56** [comment]
I'm closing this due to lack of information. If this occurs again, please re-open.
