### ISSUE TITLE
`cgreen-mocker` can't mock functions as arguments

### ISSUE THREAD

**Issue by thoni56** [cgreen-devs/cgreen#159]
If you have something like

    extern void f (void (*p1)(void*),  void *p2);

`cgreen-mocker` will generate code which doesn't mock correctly:

    void action(void *p1) { 
        mock();
    }

**Comment by joaopapereira** [comment]
The current output is:
```
void f(void (*p1)(void *), void *p2) { 
  mock(p1, p2);
}
```

and it looks correct.

**Comment by thoni56** [comment]
Yes, you are right. Perhaps this was a problem with `pycparser` in an earlier version...
