### ISSUE TITLE
Mac installer pkg & `make install` do not copy headers

### ISSUE THREAD

**Issue by nickshanks** [cgreen-devs/cgreen#164]
I had to do `$ sudo rm -r /usr/local/include/cgreen && cp -R include/cgreen /usr/local/include` to get the headers installed. The initial contents of /usr/local/include/cgreen were just a bunch of CMake files.

**Comment by thoni56** [comment]
That seems very strange.

Which Cmake did you use?

What do you mean by "Mac installer pkg"? The pkg-file from the 1.0.0 release?

**Comment by thoni56** [comment]
Ok, I tried the `.pkg`-file and it does not install correctly. Probably due to some `cmake` issue.

I'll pull that package. I suggest you install from clone.

Thanks, for the heads up.

**Comment by nickshanks** [comment]
Yes, I tried the 1.0.0 release. I have not tested the older one, that may be affected too.
But pulling the package isn't enough — I was also unable to install the headers automatically from a git clone either, by running `make install` per your documentation.

**Comment by thoni56** [comment]
Ok, so my strong suggestion is to go with the master, or the recently created 1.1.0 release.

The package is made with Cmake's package installer feature. Sorry, that it didn't work. But checking out 1.0.0 from the repo, building and installing it gives the following output, indicating that that at least worked:

    [100%] Built target cgreen_runner_tests
    Install the project...
    -- Install configuration: ""
    -- Installing: /usr/local/include/cgreen/assertions.h
    -- Installing: /usr/local/include/cgreen/boxed_double.h
    -- Installing: /usr/local/include/cgreen/breadcrumb.h
    -- Installing: /usr/local/include/cgreen/cdash_reporter.h
    -- Installing: /usr/local/include/cgreen/cgreen.h
    -- Installing: /usr/local/include/cgreen/constraint.h
    -- Installing: /usr/local/include/cgreen/constraint_syntax_helpers.h
    -- Installing: /usr/local/include/cgreen/cpp_assertions.h
    -- Installing: /usr/local/include/cgreen/cpp_constraint.h
    -- Installing: /usr/local/include/cgreen/cute_reporter.h
    -- Installing: /usr/local/include/cgreen/mocks.h
    -- Installing: /usr/local/include/cgreen/string_comparison.h
    -- Installing: /usr/local/include/cgreen/reporter.h
    -- Installing: /usr/local/include/cgreen/runner.h
    -- Installing: /usr/local/include/cgreen/suite.h
    -- Installing: /usr/local/include/cgreen/text_reporter.h
    -- Installing: /usr/local/include/cgreen/unit.h
    -- Installing: /usr/local/include/cgreen/vector.h
    -- Installing: /usr/local/include/cgreen/internal/unit_implementation.h
    -- Installing: /usr/local/include/cgreen/internal/mock_table.h
    -- Installing: /usr/local/include/cgreen/internal/mocks_internal.h
    -- Installing: /usr/local/include/cgreen/internal/suite_internal.h
    -- Installing: /usr/local/include/cgreen/internal/assertions_internal.h
    -- Installing: /usr/local/include/cgreen/internal/c_assertions.h
    -- Installing: /usr/local/include/cgreen/internal/cpp_assertions.h
    -- Installing: /usr/local/include/cgreen/internal/cgreen_pipe.h
    -- Installing: /usr/local/include/cgreen/internal/cgreen_time.h
    -- Installing: /usr/local/include/cgreen/internal/runner_platform.h
    -- Installing: /usr/local/include/cgreen/internal/function_macro.h
    -- Installing: /usr/local/lib/libcgreen.1.0.0.dylib
    -- Installing: /usr/local/lib/libcgreen.1.dylib
    -- Installing: /usr/local/lib/libcgreen.dylib
    -- Installing: /usr/local/bin/cgreen-runner
    thomasmacbook:build thomas$ git status
    HEAD detached at 1.0.0
    nothing to commit, working tree clean

Sorry for the inconvenience.
