### ISSUE TITLE
`times` (#174) broke unfulfilled expectations tallying

### ISSUE THREAD

**Issue by thoni56** [cgreen-devs/cgreen#177]
Merging #70 broke the function of tallying multiple unfulfilled expectations. This was undetected during merge since we are obviously missing "official" tests for this scenario. It was discovered during documentation updates since one of the tutorial sources actually exhibits this.

A simple test to exhibit the problem is

    Ensure(Mocks, should_detect_two_unfulfilled_expectations_on_unknown_functions) {
        expect(f1, will_return('a'));
        expect(f2, will_return('b'));
    }

And, no, you don't need to declare `f1` and `f2` to exhibit the broken behaviour. The expected output would of course be

    mock_messages_tests.c: Failure: Mocks -> should_detect_two_unfulfilled_expectations_on_unknown_functions
        Expected call was not made to mocked function [f1]
    mock_messages_tests.c: Failure: Mocks -> should_detect_two_unfulfilled_expectations_on_unknown_functions
        Expected call was not made to mocked function [f2]

The broken version only reports the first unfulfilled expectation, losing the second.

If you remove the constraints (`will_return()`) from both the expectations it will instead cause an infinite loop over "not made to [f2]".

Any input here, @joaopapereira, before I dig into debugging this?

**Comment by joaopapereira** [comment]
Where you able to fix it? @thoni56

**Comment by thoni56** [comment]
Yes. It was a simple reuse of a loop variable. Fixed by #177 in https://github.com/cgreen-devs/cgreen/commit/edc82b9d805c0f3e723bb47f9becb614758f6099. Thanks for checking up!
