### ISSUE TITLE
reporter_start function not found

### ISSUE THREAD

**Issue by occam25** [cgreen-devs/cgreen#181]
Hi,
In Cgreen documentation, in the section where it explains how to change Cgreen reporting it says:
_void (startsuite)(TestReporter reporter, const char name, const int count)
This is the first of the callbacks. At the start of each test suite Cgreen will call this method on the reporter with the name of the suite being entered and the number of tests in that suite. The default version keeps track of the stack of tests in the breadcrumb pointer of TestReporter. If you make use of the breadcrumb functions, as the defaults do, then you will need to call **reporter_start()** to keep the book keeping in sync._

But I don't find the reporter_start() function. What is it? where is it defined? if I try to use it, as the documentation suggest, I get an 'implicit declaration of function reporter_start' error. (Same with reporter_finish). I have searched for it in Cgreen sources but I don't find it.
What am I missing? : /

**Comment by thoni56** [comment]
I think you are missing the latest version of the documentation ;-)

At some point for quite some time ago, the reporter functions were harmonized. The section you refer to reads, in the [recent version of the documentation](https://cgreen-devs.github.io/chap7.html#reporter):

 > ... If you make use of the breadcrumb functions, as the defaults do, then you will need to call `reporter_start_suite()` to keep the book-keeping in sync.

At least I hope that is the problem.

**Comment by thoni56** [comment]
Was this your problem? If so do you mind closing the issue?

**Comment by thoni56** [comment]
Thanks.
