### ISSUE TITLE
Mocking C library functions

### ISSUE THREAD

**Issue by damienflament** [cgreen-devs/cgreen#182]
Hi !

I'm experimenting different C testing libraries and fall in love for CGreen, mostly due to its BDD notation, the `cgreen-runner` and the easy debugging thanks to the `CGREEN_NO_FORK` environment variable.

So, I'm rewriting my unit tests from Criterion/Mimick to CGreen.

## Mocking a function from dependency library
I wrote a unit test which checks the return value of a CUT function. This function calls a dependency library function (`libevdev_get_name` from **libevdev**). Mocking it is easy:

```c
#include "src/Device.private.h"

#include <cgreen/cgreen.h>
#include <cgreen/mocks.h>
#include <libevdev/libevdev.h>

static Device device = NULL;

Describe(device);

BeforeEach(device)
{
  device = device_create();
}

AfterEach(device)
{
  device_destroy(device);
}

const char *libevdev_get_name(const struct libevdev *dev)
{
  return (char *) mock(dev);
}

Ensure(device, has_a_name)
{
  expect(libevdev_get_name, will_return("Foo Bar"));

  assert_that(device_get_name(device), is_equal_to_string("Foo Bar"));
}
```

## Mocking a function from the C library
Now, I want to wrote a unit test which check the return value of a CUT function and the value of `errno`. This function calls the `malloc` function. The goal is to simulate a lack of memory by making `malloc` return `NULL` and by setting `errno` to `ENOMEM`.

### Implementation using CGreen

```c
#include "src/Device.private.h"

#include <cgreen/cgreen.h>
#include <cgreen/mocks.h>
#include <errno.h>

static Device device = NULL;

Describe(device_erros);

BeforeEach(device_erros)
{
}

AfterEach(device_erros)
{
}

void *malloc(size_t bytes)
{
  return (void *) mock(bytes);
}

Ensure(device_erros, a_lack_of_memory_is_reported_on_creation)
{
  expect(malloc, will_return(NULL));

  device = device_create();

  assert_that(device, is_null);
  assert_that(errno, is_equal_to(ENOMEM));
}
```

Here, the mock isn't called:
```console
Running "vostro-unit-tests" (5 tests in 1 libraries)...
/home/damien/Code/vostrod/test/device_errors.c:30: Failure: device_errors -> a_lack_of_memory_is_reported_on_creation
        Expected [device] to [be null]

/home/damien/Code/vostrod/test/device_errors.c:31: Failure: device_errors -> a_lack_of_memory_is_reported_on_creation
        Expected [(*__errno_location ())] to [equal] [ENOMEM]
                actual value:                   [0]
                expected value:                 [12]

/home/damien/Code/vostrod/test/device_errors.c:26: Failure: device_errors -> a_lack_of_memory_is_reported_on_creation
        Expected call was not made to mocked function [malloc]

  "device_errors": 3 failures in 1ms.
  "device": 7 passes in 1ms.
Completed "vostro-unit-tests": 7 passes, 3 failures in 2ms.
```

### Implementation using Criterion/Mimick
The working test implemented using Criterion/Mimick is shown below:

```c
#include "src/Device.private.h"

#include <criterion/criterion.h>
#include <errno.h>
#include <mimick.h>

mmk_mock_define(malloc_mock, void *, size_t);

Test(Device, a_lack_of_memory_is_reported_on_device_creation)
{
  mmk_mock("malloc", malloc_mock);

  mmk_when(malloc(mmk_any(size_t)), .then_return = NULL, .then_errno = ENOMEM);

  device = device_create();

  cr_assert_null(device);
  cr_assert_eq(errno, ENOMEM);
}
```

How to successfully mock `malloc` ? Is CGreen able to mocks those C functions ?

Thanks.

**Comment by damienflament** [comment]
The previous behavior was experimented using the `cgreen-runner` and building the tests as a shared library. But it makes debugging difficult.

So I decided to use explicit suites creation and running and to build a tests executable. In doing so, the mocks are called. It works fine with the `open` function, but mocking `malloc` makes the test executable fails due to a segmentation fault.

I think the mock is used by the CGreen library. So, how to mock `malloc` using CGreen ?

**Comment by thoni56** [comment]
1. To make debugging easier you can try the `cgreen-debug` which is available in recent versions. (In some environments debugging shared libraries are problematic anyway.)

1. Mocking `malloc` and other fundamental library functions is a problem. You might run into problems in your own tests too if you actually mock `malloc` since tests then cannot allocate memory.

What Criterion/Mimick seems to do (I'm guessing here) is some type of introspection and modification of the linkage symbols. This strategy is common in more dynamic languages where you can modify symbols during run-time, this is the first time I've seen that in a complied language (except Java). Cgreen does not rely on such "magic" ;-)

What I often do in similar circumstances is to create a macro for the function, in this case e.g.

    #define malloc(x) mocked_malloc(x)

This macro should be "active" during compilation of the SUT so that it actually calls `mocked_malloc`instead. Then you can mock `mocked_malloc` in the tests and if linked correctly you can catch those calls.

**Comment by damienflament** [comment]
@thoni56 Thanks. Your macro work fine.

But while using it, I figured out that in CGreen, mocks are never expected by default (it is like calling `never_expect` at the beginning of `BeforeAll`). That means I have to mock `malloc` in all my unit tests.

It is problematic in my `BeforeAll` fixtures where unit under test is constructed. `malloc` is called internally by the SUT, but I want the real implementation to be called here.

Mimick allow resetting to the real implementation using the `mmk_reset` macro. Is there a way to do the same using CGreen mocking feature ?

**Comment by damienflament** [comment]
It seems to me that CGreen is good to mock function which are used by the SUT through _dependency injection_. The documentation shows only mocks which are passed as parameter to the tested function.

Maybe using a third-party mocking library like Mimick is required to mock other functions ?

**Comment by thoni56** [comment]
I suppose you could extend the "macro approach" to include testing a global variable that you can set at your conveniences to call the real or mocked implementation as you see fit. The call to `mmk_reset` would then be a simple assignment to that variable instead.

**Comment by thoni56** [comment]
Is there anything else you'd like to discuss here? Otherwise I'll probably close this issue in some near future.

**Comment by damienflament** [comment]
Thanks for your help.
