### ISSUE TITLE
Allow mock to set global variable value

### ISSUE THREAD

**Issue by damienflament** [cgreen-devs/cgreen#187]
Currently, CGreen allows a mock to set the value of one of its parameters.

It is sometimes required to also set the value of a global parameter. I'm thinking about `errno` which is often used by system function to notify the reason of an error instead of returning an error code.

My proposal concerning the API seems obvious:

```c

int open(const char *path, int oflag)
{
  return mock(path, oflag);
}

expect(open,
       when(path, is_equal_to_string("/foo/bar")),
       will_return(-1),
       will_set_variable_content(errno, ENOMEM, sizeof(errno));
```

Maybe adding some syntactic sugar for `errno` will be appreciated:

```c
expect(open,
       when(path, is_equal_to_string("/foo/bar")),
       will_return(-1),
       will_set_errno(ENOMEM);
```

N.B.: As working with global variables is not encouraged, restricting that feature to `errno` may be considered.

**Comment by matthargett** [comment]
Agreed that globals as bad (mmmkay), but they can be common in legacy code that needs to be pinned with tests before incremental refactoring can happen. I like the declarative nature of the common errno case above, and the other syntax looks okay to me.

**Comment by damienflament** [comment]
OK. This PR seems to feel the needs. A simple macro with a `set_errno` callback can be used in the test suites which use it many times.

Thanks !
