### ISSUE TITLE
Installing Cgreen Under MSYS2?

### ISSUE THREAD

**Issue by tajmone** [cgreen-devs/cgreen#188]
I'm trying to install cgreen on Windows using [MSYS2], but so far didn't have any luck. I need cgreen in order to build the [Alan IF] project (which defaults to using Cygwin, but I'd like to use MSYS2 insteaf).

These are my first attempts to use MSYS2, so I'm not confident with the tool. 

I've tried using the [cgreen-pkg] script for PACMAN under MSYS2's MinGW shell, but I get an unsolvable dependency error for "glibc":

```
myusername@MYPCNAME MINGW32 /d/cgreen-pkg
$ pacman -U cgreen-git-1.0.0.r252.5d9bc5a-1-x86_64.pkg.tar.xz
caricamento dei pacchetti in corso...
risoluzione delle dipendenze in corso...
attenzione: impossibile risolvere "glibc", una dipendenza di "cgreen-git"
:: Il seguente pacchetto non può essere aggiornato a causa di alcune dipendenze irrisolvibili:
      cgreen-git

:: Vuoi ignorare il seguente pacchetto per questo aggiornamento? [S/n] n
errore: impossibile eseguire l'operazione richiesta (impossibile soddisfare le dipendenze)
:: unable to satisfy dependency 'glibc' required by cgreen-git

```

There's @thoni56's [cgreen-cygport] script for Cygwin, but that can't be used directly in MSYS2.

I've looked at [MSYS2 porting guide] but didn't manage to come up with a solution.

Can anyone help me setup cgreen under MSYS2?

Is there any chance that a [cgreen pacman package could be made available for MSYS2]? It would be really nice to have cgreen as an officially supported MSYS2 package, as this is becoming an increasingly popular tool and alternative for Cygwin.

[MSYS2]: https://www.msys2.org/

[MSYS2 porting guide]: https://github.com/msys2/msys2/wiki/Porting

[cgreen-pkg]: https://github.com/voins/cgreen-pkg

[Alan IF]: https://bitbucket.org/alanif/alan

[cgreen-cygport]: https://github.com/cgreen-devs/cgreen-cygport

[cgreen pacman package could be made available for MSYS2]: https://github.com/msys2/msys2/wiki/Creating-Packages

**Comment by thoni56** [comment]
I've not attempted any other Windows builds except cygwin, so the only thing I can do is to point to #131 for some help (maybe?).

**Comment by thoni56** [comment]
We would very much appreciate some progress on Windows builds, but to avoid some [yak shaving](https://en.wiktionary.org/wiki/yak_shaving) I think you can build Alan without cgreen. Just do

    make CGREEN=no

**Comment by tajmone** [comment]
Thanks @thoni56,

> We would very much appreciate some progress on Windows builds, but to avoid some [yak shaving](https://en.wiktionary.org/wiki/yak_shaving) I think you can build Alan without cgreen. Just do
> 
> ```
> make CGREEN=no
> ```

I had actually did try that already and it worked fine (tried it with ARun only, and compiled without any problems). But I was hoping to setup a MSYS2 working environment, which would be more friendly to work with, with full support of all the required tools.

See my Issue on the topic:

https://bitbucket.org/alanif/alan/issues/2/add-msys2-support

I think that adding MSYS2 support is worth the trouble, especially on the long run.

**Comment by thoni56** [comment]
In the latest commit (https://github.com/cgreen-devs/cgreen/commit/76e25b17ff236ea27e5444d5825514f2fd927591) MSys2 native (Posix) builds are fully working. That means that you now can build Alan with unittests ;-)

There is less progress on Windows (W32 and W64 versions). We'll be tracking this in #131.

To be explicit, to get a working Cgreen on Msys/Posix

- use the MSYS2 native shell (not the Mingw32 or Mingw64 versions)
- clone the repo or download the sources
- in the top directory do:
   - "make unit"
   - "make install"

That should give you a `cgreen-runner` in `/usr/local/bin`. Ensure that this is in your path and you are good to go.

I created #192 for the MSYS2 package suggestion.
