### ISSUE TITLE
debian packaging

### ISSUE THREAD

**Issue by alvinchchen** [cgreen-devs/cgreen#208]
Hello,

I am going to pack cgreen and upload to debian.

However there will be lot of changes for debian folder to fit debian policy.

Could you please remove the original debian folder for me to do the further job of packaging cgreen?

Thanks!

Alvin

**Comment by thoni56** [comment]
Hi Alvin! Happy to see you, and thanks for contributing!

If you just create a PR with the changes I will gladly merge that. Have been looking for someone to do a proper debian packaging for a long time. You can do whatever is required to adopt to debian policies, the current folder is more of a hack to get started.

Just give a shout if there is something I can do.

**Comment by alvinchchen** [comment]
Hi Thoni56~ 

Thanks in advance. Your help and support are greatly appreciated.

I will do the following steps.
1) Send ITP adoption request to Debian (done) 
2) upload cgreen to Debian Salsa server (https://salsa.debian.org/)
3) And I will add debian files to it on Salsa server.

And because cgreen has Debian files in its source code already. 
If I want to modify Debian files in cgreen source code.
I can not modify them directly.
I have to use a patch to overwrite it and this method is not recommended.

I also ask a Debian mentor about sending PR with the changes to cgreen. 
But he said it would make salsa and GitHub have duplicated cgreen code.
So sending PR is not recommended as well.

He said the best practice is.

Your help to remove the current debian folder from github.
And I will continue to step 2 and step 3 on salsa.

Thanks! :)
Alvin.

**Comment by thoni56** [comment]
Aah. I was thinking that you could issue a PR to change whatever is required in the cgreen repo. But if it is just a matter of deleting the complete directory I can do that so you don't have to issue one.

Just give me a minute...

Done.

**Comment by alvinchchen** [comment]
Hi thoni56, Thanks for your help.
I will update my progress to you. :)

**Comment by jjg-dressipi** [comment]
Great to hear this is happening, just a note to mention the removal of the Debian folder breaks a link on the front-page README.

**Comment by alvinchchen** [comment]
Hi, thanks for reminding that.

cgreen package has been put into the debian NEW queue, which requires
verification
from the ftpteam to process.

J.J. Green <notifications@github.com> 於 2020年3月30日 週一 上午6:06寫道：

**Comment by thoni56** [comment]
I'm not to familiar with debian rules and policies, but a logical place to put the packaging files (patches and scripts) would be in a new repo under `cgreen-devs`. Would that be a good idea? Or are they required to be stored somewhere else?

**Comment by thoni56** [comment]
How are this progressing @alvinchchen ? Is it possible for you to build a `.deb` using the packaging that you've made? Since the old packaging directory is now gone I'm not sure how to create a .deb package for the 1.1.3 release I'm thinking on doing in just a day or two.

Did you consider storing Debian packaging script and info in a `cgreen-dev` repo? I can create that for you.

**Comment by alvinchchen** [comment]
Hi Thoni,
It's still under processing in NEW package queue.
I can do that! Please help to create the repo.

**Comment by thoni56** [comment]
Repository created with you as a maintainer.

If I create a 1.1.3 tag/release could you build a deb-package from that for upload?

**Comment by alvinchchen** [comment]
I have uploaded the lastest debian files to the repo.

Do you mean you want to create a deb file from older version of cgreen? 

I don't know if debian files will work with it but I can try.

**Comment by thoni56** [comment]
Not from older version. I wanted to create a 1.3 release and then build a deb from that.

**Comment by thoni56** [comment]
I've hacked together (and added) a `control` (`debian-control`) that can be used to build a `.deb` locally and then built a 1.3.0 which I've uploaded. (Since I needed it for the Continous Integration for one of my projects...)

**Comment by thoni56** [comment]
According to https://repology.org/project/cgreen/versions Cgreen has reached at least a few repos, and is in the proposed for Ubuntu 20.10. So that is a big step forward! Unfortunately not any Fedora repo so far (#225).

**Comment by sampotter** [comment]
I have a question about this issue. I'm not particularly familiar with Ubuntu's packaging process, but I'm currently setting up a library I'm developing for continuous integration using Travis. It looks like cgreen is only available in Groovy and Hirsute (if I search here: https://packages.ubuntu.com/). Travis only seems to support Precise, Trusty, Xenial, Bionic, and Focal (from here: https://docs.travis-ci.com/user/reference/linux/). 

I'm wondering if it would be worth trying to backport cgreen to these distributions? To get my cgreen tests to build right now, I clone the cgreen repo (well, my fork of it, anyway ;-), and build it each time a Travis job is run. This isn't really a big deal, but installing a binary from a package manager would just run a bit faster.

(By the way, I haven't forgotten about the other issues on here that I'm involved in---things have been very hectic around here lately and haven't had a chance to get to these yet.)

**Comment by thoni56** [comment]
It is now obviously in since

    sudo apt install cgreen

works! Closing.
