### ISSUE TITLE
Is that possible to use cgreen as a single header library?

### ISSUE THREAD

**Issue by lygstate** [cgreen-devs/cgreen#232]

**Comment by thoni56** [comment]
Could you please explain more clearly what you mean?

`Cgreen` is designed so that you have to link your tests with the Cgreen library. Is that a problem for you? If so how and why? Giving more information might give us a chance to discuss what could be done in your case.

**Comment by lygstate** [comment]
For example https://github.com/catchorg/Catch2
And
https://github.com/onqtam/doctest
The distribute with a single header file.
As a unittest, we wanna not pull a lost of deps. just place a header in tests souce tree.
that's easy to intergate unittest framework.

**Comment by thoni56** [comment]
The design of `Cgreen` is towards readable and advanced features which requires both macros and a library. So no, `Cgreen` will never become a single header file solution and will always introduce a dependency to it for you project.

However, if you are on a supported platform it should be easy to build locally or install it from the repository (once it get into Fedora and Debian repositories).

It is always a "give and take" balance, I can see how a single header file solution might look tempting in some contexts.
