### ISSUE TITLE
Outdated URL for check

### ISSUE THREAD

**Issue by jjg-dressipi** [cgreen-devs/cgreen#237]
The URL for "check" on SourceForge seems to 404, I guess that they have migrated to GitHub, and this is the new address? https://github.com/libcheck/check

**Comment by jjg-dressipi** [comment]
Wow, that was fast :smile:

**Comment by thoni56** [comment]
Yeah, I'm on summer vacation (and coding ;-), I'm often hooked up to Cgreen info since I use it all the time. Appreciate reports on the little things too. But you have to act fast on them, lest they pile up. Thanks for looking at Cgreen!
