### ISSUE TITLE
Suspicious sprintf/snprintf in Android compatibility header 

### ISSUE THREAD

**Issue by ar-cetitec** [cgreen-devs/cgreen#238]
https://github.com/cgreen-devs/cgreen/blob/6a68700d1385575d5a3bc394e678a1432b9762f8/include/cgreen/internal/android_headers/androidcompat.h#L30

The two functions are redirected into Android log, but this cannot be right: they have nothing to do with output, but rather are used to format into a buffer provided by the leading argument.

I suggest just removing both macros, Bionic implementation of both is adequate.

**Comment by thoni56** [comment]
Fixed. Note: has not been tested since I'm not anywhere near an android environment. @ar-cetitec, if you can do that, it would be appreciated.

**Comment by ar-cetitec** [comment]
Unfortunately, same here. I noticed the macros while analyzing completely unrelated issue.
