### ISSUE TITLE
Test fail on ppc64le architecture

### ISSUE THREAD

**Issue by souryogurt** [cgreen-devs/cgreen#239]
I trying to build and test Cgreen on alternative architectures supported in Fedora,
It seams the test for `failure_reported_and_exception_thrown_when_messaging_would_block` fails on `ppc64le` architecture. 
Test: https://github.com/cgreen-devs/cgreen/blob/11fc9881013ac6a3ed3876c973b03a6dbdfba3c7/tests/messaging_tests.c#L43-L63

## Steps to reproduce
1. Build cgreen as usual on `ppc64le`
2. Run tests `ctest -V`

## Actual result
```console
1: /home/fedora/src/github.com/cgreen-devs/cgreen/tests/messaging_tests.c:60: Failure: messaging_tests -> failure_reported_and_exception_thrown_when_messaging_would_block 
1: 	Expected [signal_received] to [equal] [1]
1: 		actual value:			[0]
1: 		expected value:			[1]
1: 
1: /home/fedora/src/github.com/cgreen-devs/cgreen/tests/messaging_tests.c:61: Failure: messaging_tests -> failure_reported_and_exception_thrown_when_messaging_would_block 
1: 	Expected [loop] to [be less than] [LOOPS]
1: 		actual value:			[65536]
1: 		expected to be less than:	[65536]
1: 
1: /home/fedora/src/github.com/cgreen-devs/cgreen/tests/messaging_tests.c:62: Failure: messaging_tests -> failure_reported_and_exception_thrown_when_messaging_would_block 
1: 	Expected [panic_message] to [contain string] ["Too many assertions"]
1: 		actual value:			["<�~��"]
1: 		expected to contain:		["Too many assertions"]
1: 

```

**Comment by souryogurt** [comment]
I tried to debug the test on [minicloud's](https://openpower.ic.unicamp.br/minicloud/) power8 VM and found that changing `LOOPS` variable to `65537` instead of `65536` fixes the test. However, I have no idea why :)

**Comment by thoni56** [comment]
That was my first guess too. There seems to be no problem with having LOOPS to 65537 on Darwin or Linux, so I guess it only is a matter of filling the message queue.

I'll be pushing such a change in just a minute.

**Comment by souryogurt** [comment]
Just checked the patch 9768d3301590a3f826b00bdd04349c12744893df on ppc64le architecture. Confirming that patch is fixing the issue. So it can be closed.

https://koji.fedoraproject.org/koji/taskinfo?taskID=55602746
