### ISSUE TITLE
mock function which is variable length arguments?

### ISSUE THREAD

**Issue by wgqimut** [cgreen-devs/cgreen#243]
Is is possiable mock function like:
```
log(fmt, ...);
```

**Comment by thoni56** [comment]
Yes, and it's quite straight forward. The trick is to realise that the `mock()` macro/function does nothing else than take a variable and make that available for retrieval using the constraints in an `expect()`.

So what you need is a bit more code in you mock function. You need to do retrieve the vararg arguments, put them in separate variables and use them in the invocation of `mock()`. Of course if your calls to the mock will have completely different types of variable arguments (like in a format string for `print()`) you might need to re-implement the logic to parse the format and then it might be tricky to figure out how to store all of those variables. So there is no completely general solution here, like for infinite numbers of arguments with unknown types. But for a specific case you can use the pattern below.

```
#include <cgreen/cgreen.h>
#include <cgreen/mocks.h>

Describe(varargs);
BeforeEach(varargs) {}
AfterEach(varargs) {}


int logger(char *fmt, ...) {
    va_list arguments;
    int first_arg;
    int second_arg;

    va_start(arguments, fmt);
    first_arg = va_arg(arguments, int);
    second_arg = va_arg(arguments, int);
    va_end(arguments);

    mock(fmt, first_arg, second_arg);
}

void varargFunction(void) {
    logger("%d %d", 1, 2);
}

Ensure(varargs, can_be_mocked) {
    expect(logger, when(first_arg, is_equal_to(1)));
    varargFunction();
}
```

Hope that helps.

**Comment by thoni56** [comment]
Maybe this should also go in the documentation somehow.
