### ISSUE TITLE
Make fails because it tries to use `ninja` builder (on default?)

### ISSUE THREAD

**Issue by y0urself** [cgreen-devs/cgreen#279]
It seems, that 49b04d7b8a90cd65e35f34b505b025c643cdf73e broke our build command, that worked perfectly before:
```
git clone --depth 1 https://github.com/cgreen-devs/cgreen.git \
    && cd cgreen \
    && make \
    && make test \
    && make install \
    && cd .. \
    && rm -rf cgreen
```

Now fails with:
```
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/usr/local/src/cgreen/build/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:164: build/Makefile] Error 1
```

It seems, that `make` is trying to build with `ninja` on default?

**Comment by thoni56** [comment]
It should not use Ninja by default. Line 20 in the Makefile should protect against this:

> ifneq ($shell command ninja,)

I'll have a look and see if there are environments where this does not work. In the mean time you can just either delete lines 20-23 and line 25, or use `CMake` directly. Or even better, install `ninja` ;-)

What exactly do you mean by "broke our build"? Are you building `Cgreen` everytime?

**Comment by y0urself** [comment]
> What exactly do you mean by "broke our build"? Are you building Cgreen everytime?

I am using `cgreen` in docker images. These are build frequently. :)
We will just use the latest release version instead of `master` as a quick fix, I guess.

**Comment by thoni56** [comment]
You should really try Ninja then, it is ridiculously faster than using Make. CMake which actually does the builds behind the scenes can use Make or Ninja as the builder and with the convenience Makefile all you have to do is `sudo apt install ninja` to save you a bunch of seconds for each build.

So just to be clear, the Makefile in the repo is just there for convenience, it uses CMake to create the underlying build and it in turn uses a builder (make, ninja, vcs, ...) to run the builds. Three levels of build systems, how's that for incidental complexity ;-)

**Comment by y0urself** [comment]
Yeah. Thank you!
I just followed the install instructions in the INSTALL.md ...

**Comment by thoni56** [comment]
Right. I'll have a look at that and update it, it is now 6 years old ;-)

`Cgreen` is actually available in [some of the distros](https://repology.org/project/cgreen/versions) nowadays, but not always up-to-date.

**Comment by y0urself** [comment]
Yes. I have noticed, that `debian:stable` is now coming with `cgreen` package. :)
