### ISSUE TITLE
Mocking a method on a C++ class instance

### ISSUE THREAD

**Issue by pdesjardins90** [cgreen-devs/cgreen#284]
Say I have this C++ test file:

```c++
#include <cgreen/cgreen.h>
#include <cgreen/mocks.h>

#include "my_class.hxx"

using namespace cgreen;
using namespace MyNamespace;

const int SOME_DEPENDENCY_THING = 5;

MyClassDependency* my_class_dependency;
MyClass* my_class;

class MyClassDependencyMock : public MyClassDependency {
public:
  int do_some_dependency_thing(int some_argument) override {
    return (int)mock(some_argument);
  }
};

Describe(MyClass);

BeforeEach(MyClass) {
  my_class_dependency = new MyClassDependencyMock();
  my_class = new MyClass(my_class_dependency);
}

AfterEach(MyClass) {
  delete my_class;
  delete my_class_dependency;
}

Ensure(MyClass, do_something_should_delegate_to_dependency) {
  expect(my_class_dependency->do_some_dependency_thing, will_return(SOME_DEPENDENCY_THING));
  my_class->do_something();
}

```

Running this gives me this error message:

```
Failure: MyClass -> do_something_should_delegate_to_dependency 
	Mocked function [do_some_dependency_thing] did not have an expectation that it would be called

Failure: MyClass -> do_something_should_delegate_to_dependency 
	Expected call was not made to mocked function [my_class_dependency->do_some_dependency_thing]
```

The runner doesn't seem to understand that I'm referring to the mocked method of the instance, is it normal? Am I doing this wrong?

Is there any way to handle C++ class-level mocks instead of method stubs like this? It's really verbose and I haven't found anything in the documentation about it

**Comment by thoni56** [comment]
Sorry for the long delay.

I haven't been evolved in developing, or thinking, the C++ support. I do know, though, that the mocking feature of Cgreen only mocks functions. But the sixth bullet in the feature list says

    built-in mocking for C, compatible with mockitopp and other C++ mocking libraries

which kind of hints at you should look at other libraries for C++ mocking. Hope that helps somewhat.

**Comment by pdesjardins90** [comment]
@thoni56 yeah well I ended up rewriting my tests with gtest/gmock, which is a bit disappointing really because I think the overall semantics of this library are better

**Comment by matthargett** [comment]
For C++ classes, I'd recommend using [@tpounds/mockitopp ](https://github.com/tpounds/mockitopp), which I contributed to at the same time as I was contributing to cgreen, and used them both together any several MLOC+ code bases. I believe you'll still find them to fit nicely together, where mockitopp gives great assert failure messages due to its crafty use of RTTI and cross-platform C++ ABI standards.

Being able to standardize on cgreen assertions across mixed C and C++ (kernel + userland) projects, and then sprinkle in mockitopp for dynamic mocking, was a dynamite combination I don't think I've seen improved upon in the open source realm for high-performance networking, video games, VR, and other product categories that almost always need to bridge asm, C, and C++ code assets, across geographically disparate teams, in a high-quality way.

I hope this helps!

**Comment by pdesjardins90** [comment]
@matthargett I was looking for an all-in-one solution to avoid compatibility issues, but you certainly caught my curiosity. I'll make a branch to try cgreen+mockitopp on for size. Thank you guys for your help. 

Still, I think a built-in c++ mocking option would benefit this project, while still allowing other solutions maybe

**Comment by matthargett** [comment]
> @matthargett I was looking for an all-in-one solution to avoid compatibility issues, but you certainly caught my curiosity. Thank you guys for your help.

no problem! The main difficulty is that the `__FUNCTION__` built-in doesn’t give the fully resolved C++ name, which can cause all kinds of confusion when you have pure virtual interfaces and can’t distinguish between the different sub-classes, so a C++ implementation would be wholly divergent from the C implementation approach.


> Still, I think a built-in c++ mocking option would benefit this project, while still allowing other solutions maybe

I agree, and we tried a bunch of things between 2008-2013 when I was active on the project(s). It’s a different era of compilers now, though, so maybe worth revisiting!
