### ISSUE TITLE
Ability to return captured values by mocks.

### ISSUE THREAD

**Issue by oniboni** [cgreen-devs/cgreen#296]
# Problem description
In mocks, return values get stored away, which makes any manipulation via other constrains impossible. To be able to get a `late evaluation` of the current value on mock return time, we need to get the current value. Sadly, `will_return_by_value` does copy the contents in its own allocated storage.

# Example
```c
ssize_t send_data(void *data, size_t data_len) {
  return (ssize_t)mock(data, data_len);
}

// [...]
Expect(SUT, some_test_where_data_needs_to_be_sent) {
  // Prepare
  ssize_t data_len_capture = 0;

  // Expect
  expect(send_data, will_set_contents_of_parameter(data_len, data_len_capture, sizeof(data_len_capture)),
         will_return_by_value(data_len_capture));
  expect(send_data, will_set_contents_of_parameter(data_len, data_len_capture, sizeof(data_len_capture)),
         will_return(data_len_capture));

  // Act
  SUT_function_call(); // send_data, will always return `0`, bc of [1]
  SUT_function_call(); // send_data, will always return `0`, bc of [1]

  // Assert
}
```
[1]  [`stored_result`](https://github.com/cgreen-devs/cgreen/blob/a67eb4aed742365cd175540372e5f94ff82f998c/src/mocks.c#L220)

# Suggestion
Add a `will_return_by_reference` constraint.

**Comment by oniboni** [comment]
# Solution
as proposed https://github.com/cgreen-devs/cgreen/pull/297#issuecomment-1123454344
```c
ssize_t send_data(void *data, size_t data_len) {
  return *(*ssize_t)mock(data, data_len);
}

// [...]
Expect(SUT, some_test_where_data_needs_to_be_sent) {
  // Prepare
  ssize_t data_len_capture = 0;

  // Expect
  expect(send_data, will_set_contents_of_parameter(data_len, data_len_capture, sizeof(data_len_capture)),
         will_return(&data_len_capture));

  // Act
  SUT_function_call();

  // Assert
}
```

**Comment by thoni56** [comment]
Thank you, @oniboni for this issue and discussion!
 
A couple of things comes to mind from this:

- We should have a section in the documentation about these "tricks" (accessing a field in a parameter struct is another such case)
- We should think about "early" and "late" values in the constraints, perhaps use that as terms in the documentation
- Perhaps `return_by_value()` should be named differently, or perhaps even removed
