### ISSUE TITLE
CMake warning: Could NOT find LibBfd

### ISSUE THREAD

**Issue by KivApple** [cgreen-devs/cgreen#298]
I use Cgreen inside my project using add_subdirectory to avoid necessity for user to install anything except CMake and C/C++ compiler to build my project. I get annoying warnings like

```
-- Could NOT find LibBfd (missing: LIBBFD_LIBRARY LIBIBERTY_LIBRARY LIBBFD_INCLUDE_DIRS) 
CMake Warning at lib/cgreen/tools/CMakeLists.txt:45 (message):
  libbfd not found, cgreen-runner will not be built
```

But missing of cgreen-runner is fine for me and expected behavior. Is it possible to add some option to explicitly disable building of cgreen-runner and get rid of this warning?

**Comment by thoni56** [comment]
In [9cbc397ed62024f630b8bc2c338b03f7726aa8e4 ](https://github.com/cgreen-devs/cgreen/commit/9cbc397ed62024f630b8bc2c338b03f7726aa8e4) I've added a CMake variable, `CGREEN_BUILD_RUNNER`, that actively selects/deselects building the auto-discovering runner.

I'm no CMake expert so I don't know if this will prevent trying to find `libbfd`, but it's a start.

Could you please try it?

**Comment by KivApple** [comment]
Yes, the warning has gone. Thank you!

**Comment by thoni56** [comment]
Now I only have to make that official by documenting it.

**Comment by thoni56** [comment]
Closing this as we will be reverting the use of `libbfd` as outlined in #302
