### ISSUE TITLE
cannot pass unit test in i386 

### ISSUE THREAD

**Issue by gavin09** [cgreen-devs/cgreen#313]
I am coworking with szlin to package the newest cgreen (1.6.1) to Debian.

i386 architecture cannot pass the unit test with the default build type [1]. However, the unit test passes if I assign "CMAKE_BUILD_TYPE=Debug" [2]. 

The detailed log of the default build type can be found here: https://salsa.debian.org/gavinlai-guest/cgreen/-/jobs/3988529/artifacts/browse/debian/output/source_dir/build/Testing/Temporary/

[1]: https://salsa.debian.org/gavinlai-guest/cgreen/-/pipelines/504784
[2]: https://salsa.debian.org/gavinlai-guest/cgreen/-/pipelines/504790

**Comment by thoni56** [comment]
With just a quick look at the log that might be related to a [fix](75ec9d13bba0a582871b63313ed9b66f753ba20b) that is done after 1.6.1. Could you just try the same tests with HEAD. If that passes I can release a 1.6.2.

**Comment by gavin09** [comment]
Thanks for your prompt reply! It passes the test in i386 [1] with the HEAD commit (98c2550). 
A release of 1.6.2 will be appreciated : )

[1] https://salsa.debian.org/gavinlai-guest/cgreen/-/pipelines/505623

**Comment by thoni56** [comment]
Release 1.6.2 published!

I don't know what the plans for the packaging structure is at this point, put I found it to be a bit ... surprising for some old packaging I tried. It probably followed Debian "rules", but as a user of the package I found the partitioning unnatural for a app that is only used by developers.

So if I may, I'd like to request that an installation of `cgreen1` includes both the tools, the library and the header files, as all those are required when using `Cgreen`. In a manner, there is no "app" package, only the "-dev" package.

Again, that is only my suggestion for making the package easier to install for the "users", which are always "developers".

**Comment by gavin09** [comment]
After reading your comments, I read the Debian policy again carefully. I think the maintainer separates the files into packages correctly.

However, I know users need the tools, library, and header files in general. Command "apt-get install cgreen1" simply install these things would be easier for the users.

Here's my approach:
Instead of putting tools, the library, and the header files into "cgreen1" package, I think we just need to make sure the command "apt-get install cgreen1" installs the files we expect.
The current situation is cgreen1 depends on libcgreen1, so I don't need to handle this part. It will definitely install libcgreen1 when "apt-get install cgreen1". The only thing I need to handle is the header files. I think the most precise relationship in debian/control is Recommends. 

> Recommends
>     This declares a strong, but not absolute, dependency.
>     The Recommends field should list packages that would be found together with this one in all but unusual installations.

By default, "apt-get install" will also install "Recommends" packages.
I will add "Recommends libcgreen1-dev" into cgreen1. With this, "apt-get install cgreen1" will install the files we expect.
I hope my approach can fit your suggestion.

However, my change still needs to be reviewed by Debian procedure, so I cannot promise anything at this moment. Maybe I miss something.

**Comment by thoni56** [comment]
Yes, I think that is an approach that will work. Hope it passes Debian scrutiny ;-) Perhaps there is a way  to add a comment to the reason for doing so.

**Comment by thoni56** [comment]
Any update on this? Repology indicates that a few platforms has moved to 1.6.2 but not Debian, and thus not Ubuntu...

**Comment by gavin09** [comment]
Unfortunately, there was a freeze policy at that moment. Debian just opened to upload new packages after Debian 12 was released.

Now, I am looking into a warning in the man page [1].  I hope I can upload 1.6.2 or a newer version to Debian when I resolve this issue. 

[1] https://gavinlai-guest.pages.debian.net/-/cgreen/-/jobs/4560875/artifacts/debian/output/lintian.html

**Comment by gavin09** [comment]
> Unfortunately, there was a freeze policy at that moment. Debian just opened to upload new packages after Debian 12 was released.
> 
> Now, I am looking into a warning in the man page [1]. I hope I can upload 1.6.2 or a newer version to Debian when I resolve this issue.
> 
> [1] https://gavinlai-guest.pages.debian.net/-/cgreen/-/jobs/4560875/artifacts/debian/output/lintian.html

I just had a pull request in https://github.com/cgreen-devs/cgreen/pull/322 to fix the lintian. Please have a review. Thanks!
