### ISSUE TITLE
offer a mechanism to skip tests at runtime

### ISSUE THREAD

**Issue by tych0** [cgreen-devs/cgreen#326]
I see the documented https://cgreen-devs.github.io/cgreen/cgreen-guide-en.html#xensure `xEnsure` macro, but I have a test where I want to skip things at runtime (based on whether or not the kernel I'm using has new enough features). I don't see a way to do this, but it would be nice to have.

**Comment by thoni56** [comment]
A simple way to at least not fail tests that are dependent on run-time features is to use `pass_test()`:

    if (<run-time condition not met>)
        pass_test();
    else {
        .... // the actual test
    }

There is also `fail_test()`, not no `skip_test()` which probably would not be to hard to implement.

**Comment by tych0** [comment]
Yep, I've done an even simpler `return;`, but it would be nice to have it show up as skipped in the final stats.

**Comment by thoni56** [comment]
I just commited 1.6.4 which includes `skip_test()`.
