### ISSUE TITLE
Not installed on correctly on OSX.

### ISSUE THREAD

**Issue by agirorn** [cgreen-devs/cgreen#35]
The experience on mac for this project is far from optimal. When following the tutorial https://cgreen-devs.github.io/#_installing_cgreen I checkout out the code and run `make && make test` and that seams to be ok. Then I run `make` install and nothing happens and I assume at least it installed something to my system to make testing suer easy. Then I try to build first_test.c with this command `gcc -v -c first_test.c` and I get: 
```shell
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.10.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name first_test.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 253.6 -v -dwarf-column-info -coverage-file /Users/agir/code/using-cgreen/first_test.c -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0 -fdebug-compilation-dir /Users/agir/code/using-cgreen -ferror-limit 19 -fmessage-length 101 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.10.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o first_test.o -x c first_test.c
clang -cc1 version 7.0.0 based upon LLVM 3.7.0svn default target x86_64-apple-darwin14.5.0
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
first_test.c:1:10: fatal error: 'cgreen/cgreen.h' file not found
#include <cgreen/cgreen.h>
         ^
1 error generated.
```

Which I can fix by adding C_INCLUDE_PATH so I run it a second time like this.

```shell
C_INCLUDE_PATH=~/code/cgreen/include gcc -v -c first_test.c
```

That works so move on to the next command `gcc first_test.o -lcgreen -o first_test` and does not work.

```shell
ld: library not found for -lcgreen
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This command needs to be fixed: `gcc first_test.o -L`pwd`/../cgreen/build/build-c/src/ -lcgreen -o first_test`

Then I try to run the test `./first_test` and I get this.

```shell
dyld: Library not loaded: @rpath/libcgreen.1.dylib
  Referenced from: /Users/agir/code/using-cgreen/./first_test
  Reason: image not found
[1]    31142 trace trap  ./first_test
```

And this command needs to be fixed like this. `DYLD_LIBRARY_PATH=~/code/cgreen/build/build-c/src/ ./first_test`

I assume this can be fixed by having `make install` copy Cgreen to the proper location.

**Comment by thoni56** [comment]
It is correct that `make install` in the top level of the source does not currently do anything.

This is because cgreen by default builds both for C and C++ and on some systems you can't have both of those installed at once yet.

So you have to navigate to `build/build-c` or `build/build-c++` and do `make install` from there.

By default it installs in `/usr/local` which may or may not be included in your default search paths for include files and libraries. You may tweak the installation directory by altering the CMake configuration in `build/build-c/` and/or `build/build-c++` using `ccmake ../..`.

We are of course planning to address this at some point.

**Comment by agirorn** [comment]
Then I think the docs need to be updated to reflect this or make install should be fixed so that cgreen can be installed and used as the docs describe. Maybe the c++ version of cgreen should be renamed to cppgreen and the c only version could keep the cgreen name, then they could live side by side. At least I find it to be a major bummer for my projects c++ having to install a c++ version of cgreen be for running c++ tests and then install the c version before running the c test. I wanted to use one test tool for my c/c++ exploration.

**Comment by thoni56** [comment]
i'm working on a documentation and build script update for this.

It isn't a naming issue, the C++ library is called `cgreen++`, so you only have to link with that instead. And surround your tsts with `namespace cgreen {}`.

On OSX having both versions installed in parallel works just fine. Just navigate to `build/build-c` and `build/build-c++` respectively and do `sudo make install` there.

**Comment by agirorn** [comment]
Thank you for clearing that up.
