### ISSUE TITLE
Same 'cgreen-runner' for C and C++

### ISSUE THREAD

**Issue by thoni56** [cgreen-devs/cgreen#51]
Currently, in many environments, the reflective runner from a C++ build cannot run C built test libraries, and vice versa.

It would be great if we could use the same one for all shared test libraries. I have no idea what influences this, so there needs to be some kind of discovery or analysis effort.

It also relates somewhat to our build strategy, in that I think we should look into packaging both C and C++ libs, as well as a universal runner in the same package.

**Comment by thoni56** [comment]
Would it be possible to "automatically" wrap the shared test library when it's built in the C calling API?

I don't think that it would remove any features of the reflective runner since the exception handling is performed in the cgreen core.

**Comment by thoni56** [comment]
Hmm, on Ubuntu 15.10 with gcc 5.2.1 which ever `cgreen-runner` runs both suites just fine, except for not catching an exception correctly which might be expected. So using the C++ built `cgreen-runner` seems to be possible there. So for this case we could just build it with C++.

Maybe this is just a MacOSX and/or Cygwin issue... Have to check since I don't really remember now...

**Comment by thoni56** [comment]
Maybe this has something to do with how dynamic libraries are loaded and resolved? The C-built `cgreen-runner` is built to use `libcgreen.<ext>` but the C++ built test libraries are built to use `libcgreen++.<ext>`. They both include the same symbols and maybe `dlopen()` handles this potential conflict differently on the various platforms when it needs to load both...

**Comment by thoni56** [comment]
A suggestion for a stop-gap fix would be to name the runner `cgreen-runner++` for C++ in the same way as the library is called `libcgreen++` or some such.

At least until we can figure out if unifying the runner is even possible...

**Comment by matthargett** [comment]
I'd be very curious to understand why using a C++-built runner on a C-built tests causes a *crash* in Cygwin. does cgreen-runner link against libcgreen.so at all? if so, a C++-built runner would be linking against libcgreen++.so and a C-built test suite would be linking against libcgreen.so -- I could imagine there might be conflicts when linking to both at the same time.

Having to have 2 different runners that people have to understand how the test suites shared libs were built is a major usability problem, so I'd like to figure something out where there's one runner to rule all the suites.

**Comment by thoni56** [comment]
Totally agree on the usability.

I've been pondering if it would be possible to do away with the C++/C divide completely.

Wouldn't it be possible to build a cgreen-library which contains both C++ API with mangled names and the C API with "straight" names? I'm thinking careful placement of `#ifdef _cplusplus_ extern "C";`.

**Comment by thoni56** [comment]
Given that we think that the C/C++ divide is a root cause of this, I'm thinking that a library with a C _and_ C++ API could exist if we made the project a mixed language project by compiling most things, particularly `assertions.c` (where `assert_that_()` lives) with C and particularly `cpp_assertions.cpp` with C++.

In effect we'd be using Cgreen's core, `assert_that_()`, as an extern "C" function from the C++ "module" `cpp_assertions.cpp` in a way that a C++ user project.

Would that be possible?

**Comment by thoni56** [comment]
OK, so a comment in `include/internal/c_assertions.h` says that we can't have `assert_that_()` extern C because then we can't overload it. This could be solved by pushing that functionality down one level to `assert_that_core()` (say) which would be the core functionality in extern "C" that would be called upon to do the work for C and C++.

Both C and C++ projects could be made to call this either directly or through C++ mangled overloaded functions (like today) inside the library.

**Comment by thoni56** [comment]
I have hacked a version that do this, I think, on [my `unify_c_and_c++ branch`](/thoni56/cgreen/tree/unify_c_and_c++). So it seems feasible. I've created #73 to handle this and included that in what's in the 1.0.0 release. So, I'll be closing this issue in the near future.

Implementation details:
- renamed the `assert_that_()` implementation in the library to `assert_core_()` (suggestions for a better name are welcome, `assert_that_implementation()`?)
- changed the headers so that 
  - in C mode all `assert_that()` are dispatched directly to `assert_core_()`
 - in C++ mode all `assert_that()` have C++ overloaded versions for all types, including the basic `assert_that()` (not only the string versions)
- implemented the new C++ `assert_that()` as a simple dispatch to the C version `assert_core()`
- modified the C++ string handling overloaded `assert_that()` to use the C version `assert_core()`

This gives a `libcgreen.<ext>` with the following content:

    thomasmacbook:cgreen thomas$ nm build/build-c/src/libcgreen.dylib | grep assert_
    0000000000008150 T __ZN6cgreen12assert_that_EPKciS1_PKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEP11Constraint_
    00000000000080e0 T __ZN6cgreen12assert_that_EPKciS1_RKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEP11Constraint_
    00000000000080d0 T __ZN6cgreen12assert_that_EPKciS1_lP11Constraint_
    0000000000001a40 T _assert_core_
    0000000000001d70 T _assert_double_equal_
    0000000000001e00 T _assert_double_not_equal_
    0000000000001c90 T _assert_equal_
    0000000000001d00 T _assert_not_equal_
    0000000000001e90 T _assert_string_equal_
    0000000000001f40 T _assert_string_not_equal_
    0000000000001b70 T _assert_that_double_
    00000000000069e0 t _assert_true
    00000000000037e0 T _significant_figures_for_assert_double_are

Need to duplicate the basic tests with a C++ compiled version to ensure that everything works in C++ too, before doing away with the special C++ build. Also remove all `WITH_CXX`. But that's work that will be done on #73.

**Comment by thoni56** [comment]
Now that the C and C++ unification is resolved, this is no longer an issue.
