### ISSUE TITLE
Do we need `is_equal_to_unsigned`? `hex` or `byte`?

### ISSUE THREAD

**Issue by thoni56** [cgreen-devs/cgreen#53]
I was flipping through James Grennings *TDD for Embedded C* where he is mainly using CppUTest, but initially also Unity. He does this basically:

    TEST(sprintf, NoFormatOperations)​ {
        ​char​ output[5];​
        memset(output, 0xaa, ​sizeof​(output));
        TEST_ASSERT_BYTES_EQUAL(0xaa, output[4]);​
    }

Obviously, I'm no fan of the SHOUTING style ;-) but there seems to be no way to do exactly the same in Cgreen since we don't have `is_equal_to_byte()`.

Here are some attempts:

    Ensure(Char, can_compare_to_hex_without_cast) {
      char chars[4] = {0xaa, 0xaa, 0xaa, 0};
      assert_that(chars[0], is_equal_to(0xaa));
    }
    Ensure(Char, can_compare_to_hex_with_cast_expected_to_signed) {
      char chars[4] = {0xaa, 0xaa, 0xaa, 0};
      assert_that(chars[0], is_equal_to((signed)0xaa));
    }
    Ensure(Char, can_compare_to_hex_with_cast_actual_to_unsigned) {
      char chars[4] = {0xaa, 0xaa, 0xaa, 0};
      assert_that(((unsigned)chars[0]), is_equal_to(0xaa));
    }

Resulting in

    Running "char_tests" (4 tests)...
    char_tests.c:19: Failure: Char -> can_compare_to_hex_with_cast_actual_to_unsigned
        Expected [((unsigned)chars[0])] to [equal] [0xaa]
                actual value:                   [4294967210]
                expected value:                 [170]
    char_tests.c:14: Failure: Char -> can_compare_to_hex_with_cast_expected_to_signed
        Expected [chars[0]] to [equal] [(signed)0xaa]
                actual value:                   [-86]
                expected value:                 [170]
    char_tests.c:9: Failure: Char -> can_compare_to_hex_without_cast
        Expected [chars[0]] to [equal] [0xaa]
                actual value:                   [-86]
                expected value:                 [170]

Which, of course, is caused by the signededness of the built in `char` and C sign-extending actual arguments.

I've only found one way to make this test pass:

    Ensure(Char, can_compare_to_hex_with_actuals_type_unsigned) {
      unsigned char chars[4] = {0xaa, 0xaa, 0xaa, 0};
      assert_that(chars[0], is_equal_to(0xaa));
    }

Note the move to `unsigned char`. We certainly don't want to force users to change their datatypes to get Cgreen tests to work.

Alternatives are of course to go for more `is_equal_to_X()` or figure out the signedness of the argument type of the actual (which I'm not sure can be done even theoretically).

The fact that this does not work in a natural way would/could trip an unsuspecting TDD:er onto a long hunt for a problem that isn't there.

Suggestions?

**Comment by thoni56** [comment]
I can't figure out a way to address this since `assert_that_()` (which is the first real function in the macro chain starting from `assert_that()`) takes `intptr_t actual` as an argument. At this point C will sign-extend the `char` sent and then there is no way to "unsign-extend" it later.

So maybe this must be solved with a "documentation fix", i.e. clearly explain this phenomenon. And add another item in the "Tips" chapter.

I'd like to make it more evident that this happens, perhaps a `is_equal_to_hex()` that displays the expected and actual values in hex would make it more obvious that it is actually the same value but sign-extended:

    char_tests.c:9: Failure: Char -> can_compare_to_hex_without_cast
        Expected [chars[0]] to [equal] [0xaa]
            actual value:                   [0xfffffffffffffaa]
            expected value:                 [0xaa]

**Comment by thoni56** [comment]
Of course, I forgot the case with the correct cast (my understanding of the cast to `unsigned` was flawed...):

    Ensure(Char, can_compare_to_unsigned_char) {
      char chars[4] = {0xaa, 0xaa, 0xaa, 0};
      assert_that(((unsigned char)chars[0]), is_equal_to(0xaa));
    }

Note the cast to `unsigned char`, not just `unsigned`. This passes.

I still think the `is_equal_to_hex()` would be a good addition, especially in embedded environments, so I'll look into that.

**Comment by matthargett** [comment]
thanks for looking at other frameworks and finding our blind spots :)

maybe is_equal_to_byte()? if we do that, can the C++ version of assert_that_<> do the conversions properly?

**Comment by thoni56** [comment]
I've been thinking about 'byte' also. Although we have a common understanding about what it means, there is no byte datatype in C or C++ natively. So I'm not sure an `is_equal_to_byte()` would actually match the users 'byte', typedef or macro, and the same sign-extension problem could show up. How would we interpret `assert_that(0xffee, is_equal_to_byte(<somevalue>))`? Masking?

I'm not sure I understand what you mean with 'do the conversions properly'. Could you explain?

What I found was that both actual and expected values are implicilty cast into `intptr_t` using C and C++ rules, which seems to work except when you have wrong signedness.

I'm inclined to go for using that, documenting it and offer `is_equal_to_hex()` as an alternative to display values in a more machine-like representation.

I have an implementation that adds `_hex` and the suggested documentation. Will PR.

**Comment by thoni56** [comment]
Implemented `is_equal_to_hex()` and added som documentation in pr #54.
