### ISSUE TITLE
Updated license

### ISSUE THREAD

**Issue by thoni56** [cgreen-devs/cgreen#66]
The current license text is *so* old. It includes the "Ty Coon" signature...

Suggest update to LGPL 3.0. Do we really need to keep a separate license in the tutorial? I'd rather have a short reference in a section in the front matter or page 2.

**Comment by matthargett** [comment]
what do people think about MIT or BSD?

**Comment by thoni56** [comment]
I have no problem going from 6 pages of copyleft to one section of "remember who did the work" (at least that's my perception of the essential difference, but please correct me if I'm wrong).

Except for all participating `cgreen-devs` giving the ok, we need to check with at least @lastcraft and @joaohf, before changing the licensing, I suppose.

**Comment by d-meiser** [comment]
I don't have any strong opinions regarding the license. Whichever you find most appropriate works for me (as long as I'm still able to use cgreen  of course :-) )

**Comment by lastcraft** [comment]
Hi...

I originally had it as public domain, but copylefted it when someone in
Google stole it. I'm fine with anything permissive, but credit authors :).

yours, Marcus

On 8 April 2016 at 15:13, Dominic Meiser <notifications@github.com> wrote:

> I don't have any strong opinions regarding the license. Whichever you find
> most appropriate works for me (as long as I'm still able to use cgreen of
> course :-) )
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cgreen-devs/cgreen/issues/66#issuecomment-207472683>
>



-- 
Marcus Baker, Aframe developer, marcus@aframe.com

--

**Comment by thoni56** [comment]
Then my suggestion, after a few minutes of research ;-) is the [ISC](https://en.wikipedia.org/wiki/ISC_license) which, [according to this discussion](https://github.com/github/choosealicense.com/issues/257), should be appropriate, sufficient given current copyright laws and require an explicit copyright notice on all kinds of distributions.

Comments?

**Comment by thoni56** [comment]
E.g.

    Copyright (c) 2006-2016, Cgreen Development Team and contributors
    (https://github.com/cgreen-devs/cgreen/graphs/contributors)

    Permission to use, copy, modify, and/or distribute this software for any purpose with
    or without fee is hereby granted, provided that the above copyright notice and this
    permission notice appear in all copies.

    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHORS DISCLAIMS ALL WARRANTIES
    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR
    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

**Comment by thoni56** [comment]
Updated.
