### ISSUE TITLE
Mechanism to skip tests temporarily

### ISSUE THREAD

**Issue by thoni56** [cgreen-devs/cgreen#67]
Although I don't like the concept of having tests that are skipped in the run, in principle, I'm also a realist and know there are times when you need this. Particularly if you are adopting a better framework like Cgreen from your previous. Not having this feature might make you use comments, which is even worse.

A mechanism to indicate skipped tests will allow tallying them and making them visible, e.g. in Jenkins.

So I propose that at some point this feature is included.

**Comment by d-meiser** [comment]
Would this go in the test runner? Or are you envisioning having this mechanism at the library level?

**Comment by matthargett** [comment]
I like the convention that jsunit/jasmine has/had, where adding an 'x' to the front of the test declaration marks it as ignored. it makes for rapid editor/IDE focused loops when debugging tests, and easy to grep for manually or include in a pre-commit script.

in our case, we would make an 'xEnsure' macro. any other opinions?

**Comment by thoni56** [comment]
Exactly my thoughts.

**Comment by thoni56** [comment]
With the commits in PR #86, I consider this to be done. I used 'skip' as that seems to be the mostly used terminology, but also sounds more temporary than 'ignore', which to my, non-native English, ears, sounds a bit permanent.
