### ISSUE TITLE
Add `expect_call_count()`

### ISSUE THREAD

**Issue by thoni56** [cgreen-devs/cgreen#70]
Moved from TODO file.

I'm suspecting this implies that `expect_always()` could count the number of calls. If so, I would rather have:

```
expect_repeated(func, <constraints>, 3);
```

or even

```
expect(func, <constraints>, times(3));
```

or something similar.

**Comment by arthurpi** [comment]
That would be a great addition to cgreen!

**Comment by thoni56** [comment]
Thanks @joaopapereira for this addition!
